package gitlab

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
	status "ucode/ucode_go_function_service/api/status_http"
	"ucode/ucode_go_function_service/config"
	nb "ucode/ucode_go_function_service/genproto/new_object_builder_service"
	"ucode/ucode_go_function_service/pkg/github"

	"github.com/xanzy/go-gitlab"
)

func CommitFiles(cfg IntegrationData, branch string, files []*nb.McpProjectFiles) ([]byte, error) {
	if len(files) == 0 {
		return nil, errors.New("no files provided")
	}

	existingFiles, err := GetRepoFilesMap(cfg, branch)
	if err != nil {
		return nil, fmt.Errorf("could not check existing files: %w", err)
	}

	var actions []CommitAction

	for _, file := range files {
		actionType := "create"
		if existingFiles[file.Path] {
			actionType = "update"
		}

		actions = append(actions, CommitAction{
			Action:   actionType,
			FilePath: file.Path,
			Content:  file.Content,
			Encoding: "text",
		})
	}

	commitReq := CommitRequest{
		Branch:        branch,
		CommitMessage: "generated by Fazliddin",
		Actions:       actions,
	}

	url := fmt.Sprintf("%s/api/v4/projects/%d/repository/commits",
		cfg.GitlabIntegrationUrl,
		cfg.GitlabProjectId)

	return DoRequestV1(url, cfg.GitlabIntegrationToken, http.MethodPost, commitReq)
}

// PromoteUGenToMaster syncs the u-gen branch to master by committing all u-gen
// files to master in a single commit. Files that exist on master but not on u-gen
// (and are not skipped CI/asset files) are deleted so master exactly mirrors u-gen.
// templateProjectID is the GitLab ID of the React template repo — its package.json
// and package-lock.json are always restored on master to keep npm ci in sync.
// This is the API-level equivalent of a force push from u-gen to master.
func PromoteUGenToMaster(cfg IntegrationData, gitlabURL, token string, templateProjectID int) error {
	// Step 1: get all files from u-gen with content
	ugenFiles, err := fetchArchiveFiles(gitlabURL, token, cfg.GitlabProjectId, config.UGenBranch)
	if err != nil {
		return fmt.Errorf("failed to read %s branch: %w", config.UGenBranch, err)
	}
	if len(ugenFiles) == 0 {
		return fmt.Errorf("%s branch has no files to promote", config.UGenBranch)
	}

	// Step 2: get file paths currently on master
	masterFiles, err := GetRepoFilesMap(cfg, config.DefaultBranch)
	if err != nil {
		return fmt.Errorf("failed to read %s branch file list: %w", config.DefaultBranch, err)
	}

	// Step 3: build commit actions — create/update u-gen files, delete master-only files
	ugenPaths := make(map[string]bool, len(ugenFiles))
	var actions []CommitAction

	for _, f := range ugenFiles {
		ugenPaths[f.Path] = true
		action := "create"
		if masterFiles[f.Path] {
			action = "update"
		}
		actions = append(actions, CommitAction{
			Action:   action,
			FilePath: f.Path,
			Content:  f.Content,
			Encoding: "text",
		})
	}

	// Delete files present on master but absent from u-gen (skip CI/asset files)
	for path := range masterFiles {
		if !ugenPaths[path] && !shouldSkipFile(path) {
			actions = append(actions, CommitAction{
				Action:   "delete",
				FilePath: path,
			})
		}
	}

	// Step 4: restore package.json and package-lock.json from the React template.
	// This ensures master always has the correct lock file in sync with package.json,
	// regardless of whether a previous push corrupted them with AI-generated versions.
	templateCfg := IntegrationData{
		GitlabIntegrationUrl:   cfg.GitlabIntegrationUrl,
		GitlabIntegrationToken: token,
		GitlabProjectId:        templateProjectID,
	}
	for _, pkgFile := range []string{"package.json", "package-lock.json"} {
		content, fetchErr := getFileContent(templateCfg, pkgFile, config.DefaultBranch)
		if fetchErr != nil {
			fmt.Printf("[PROMOTE] warning: could not fetch %s from template (id=%d): %v\n", pkgFile, templateProjectID, fetchErr)
			continue
		}
		action := "update"
		if !masterFiles[pkgFile] {
			action = "create"
		}
		actions = append(actions, CommitAction{
			Action:   action,
			FilePath: pkgFile,
			Content:  content,
			Encoding: "text",
		})
	}

	commitReq := CommitRequest{
		Branch:        config.DefaultBranch,
		CommitMessage: fmt.Sprintf("promote %s to %s", config.UGenBranch, config.DefaultBranch),
		Actions:       actions,
	}

	apiURL := fmt.Sprintf("%s/api/v4/projects/%d/repository/commits", gitlabURL, cfg.GitlabProjectId)
	result, err := DoRequestV1(apiURL, token, http.MethodPost, commitReq)
	if err != nil {
		return fmt.Errorf("commit request failed: %w", err)
	}

	// Check for GitLab-level errors in the response body.
	// Success responses contain both "id" and "message" (the commit message).
	// Error responses contain only "message" with no "id".
	var resp map[string]any
	if jsonErr := json.Unmarshal(result, &resp); jsonErr == nil {
		if _, hasID := resp["id"]; !hasID {
			if msg, ok := resp["message"]; ok {
				return fmt.Errorf("gitlab commit error: %v", msg)
			}
		}
	}

	return nil
}

// getFileContent fetches the raw content of a single file from a GitLab repo via the Files API.
func getFileContent(cfg IntegrationData, filePath, ref string) (string, error) {
	encoded := strings.ReplaceAll(filePath, "/", "%2F")
	url := fmt.Sprintf("%s/api/v4/projects/%d/repository/files/%s/raw?ref=%s",
		cfg.GitlabIntegrationUrl, cfg.GitlabProjectId, encoded, ref)

	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("PRIVATE-TOKEN", cfg.GitlabIntegrationToken)

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("status %d: %s", resp.StatusCode, string(body))
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	return string(body), nil
}

func GetProjectPath(gitlabURL, token string, projectID int) (string, error) {
	apiURL := fmt.Sprintf("%s/api/v4/projects/%d", gitlabURL, projectID)
	req, err := http.NewRequest(http.MethodGet, apiURL, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("PRIVATE-TOKEN", token)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gitlab get project returned %d: %s", resp.StatusCode, string(b))
	}

	var project struct {
		Path string `json:"path"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&project); err != nil {
		return "", err
	}
	if project.Path == "" {
		return "", fmt.Errorf("gitlab project has empty path")
	}
	return project.Path, nil
}

func CreateBranch(cfg IntegrationData, branchName, ref string) error {
	apiURL := fmt.Sprintf("%s/api/v4/projects/%d/repository/branches",
		cfg.GitlabIntegrationUrl, cfg.GitlabProjectId)

	payload := map[string]string{
		"branch": branchName,
		"ref":    ref,
	}

	_, err := DoRequestV1(apiURL, cfg.GitlabIntegrationToken, http.MethodPost, payload)
	if err != nil {
		return fmt.Errorf("create branch request failed: %w", err)
	}

	return nil
}

func GetRepoFilesMap(cfg IntegrationData, ref string) (map[string]bool, error) {
	client, err := gitlab.NewClient(cfg.GitlabIntegrationToken, gitlab.WithBaseURL(cfg.GitlabIntegrationUrl+"/api/v4"))
	if err != nil {
		return nil, fmt.Errorf("failed to create gitlab client: %w", err)
	}

	var (
		filesMap = make(map[string]bool)

		opt = &gitlab.ListTreeOptions{
			Ref:       gitlab.Ptr(ref),
			Recursive: gitlab.Ptr(true),
			ListOptions: gitlab.ListOptions{
				PerPage: 100,
				Page:    1,
			},
		}
	)

	for {
		nodes, resp, err := client.Repositories.ListTree(cfg.GitlabProjectId, opt)
		if err != nil {
			return nil, fmt.Errorf("failed to list tree: %w", err)
		}

		for _, node := range nodes {
			if node.Type == "blob" {
				filesMap[node.Path] = true
			}
		}

		if resp.NextPage == 0 {
			break
		}
		opt.Page = resp.NextPage
	}

	return filesMap, nil
}

// Integration gitlab.udevs.io

func CreateProjectFork(projectName string, data IntegrationData) (response ForkResponse, err error) {
	var (
		projectId    = data.GitlabProjectId
		strProjectId = strconv.Itoa(projectId)
		resp         ForkResponse
	)

	respByte, err := DoRequestV1(data.GitlabIntegrationUrl+"/api/v4/projects/"+strProjectId+"/fork", data.GitlabIntegrationToken, http.MethodPost, CreateProject{
		NamespaceID:          data.GitlabGroupId,
		Name:                 projectName,
		Path:                 projectName,
		InitializeWithReadme: true,
		DefaultBranch:        config.DefaultBranch,
		Visibility:           "private",
	})
	if err != nil {
		return ForkResponse{}, err
	}

	if err = json.Unmarshal(respByte, &resp); err != nil {
		return ForkResponse{}, err
	}

	// Теперь избыточно (DoRequestV1 уже поймает 4xx/5xx), но оставляем как доп. защита
	if len(resp.Message) > 0 {
		message, _ := resp.Message.MarshalJSON()
		return ForkResponse{}, errors.New(string(message))
	}

	return resp, nil
}

func DoRequest(url, token string, method string, body any) (responseModel GitlabIntegrationResponse, err error) {
	data, err := json.Marshal(&body)
	if err != nil {
		return
	}

	client := &http.Client{
		Timeout: time.Duration(15 * time.Second),
	}

	url += "?access_token=" + token

	req, err := http.NewRequest(method, url, bytes.NewBuffer(data))
	if err != nil {
		return
	}
	req.Header.Add("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return
	}
	defer resp.Body.Close()

	responseModel.Code = resp.StatusCode

	respByte, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}

	if len(respByte) == 0 {
		return responseModel, nil
	}

	var emptyMap = make(map[string]any)
	if err = json.Unmarshal(respByte, &emptyMap); err != nil {
		responseModel.Message = map[string]any{"raw": string(respByte)}
		return responseModel, nil
	}

	responseModel.Message = emptyMap
	return responseModel, nil
}

func DoRequestV1(url, token string, method string, body any) ([]byte, error) {
	data, err := json.Marshal(&body)
	if err != nil {
		return nil, err
	}

	client := &http.Client{
		Timeout: 15 * time.Second,
	}

	url += "?access_token=" + token

	req, err := http.NewRequest(method, url, bytes.NewBuffer(data))
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	respByte, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Проверяем статус код — раньше ошибки GitLab молча игнорировались
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("gitlab error %d: %s", resp.StatusCode, string(respByte))
	}

	return respByte, nil
}

func UpdateProject(cfg IntegrationData, data map[string]any) (response GitlabIntegrationResponse, err error) {
	var (
		projectId    = cfg.GitlabProjectId
		strProjectId = strconv.Itoa(projectId)
	)

	resp, err := DoRequest(
		cfg.GitlabIntegrationUrl+"/api/v4/projects/"+strProjectId,
		cfg.GitlabIntegrationToken,
		http.MethodPut,
		data,
	)
	if err != nil {
		return GitlabIntegrationResponse{}, err
	}

	if resp.Code >= 500 {
		return GitlabIntegrationResponse{}, errors.New(status.InternalServerError.Description)
	}

	if resp.Code >= 400 {
		msgBytes, _ := json.Marshal(resp.Message)
		return GitlabIntegrationResponse{}, fmt.Errorf("gitlab error %d: %s", resp.Code, string(msgBytes))
	}

	return resp, nil
}

func CreateProjectVariable(cfg IntegrationData, data map[string]any) (response GitlabIntegrationResponse, err error) {
	var (
		projectId    = cfg.GitlabProjectId
		strProjectId = strconv.Itoa(projectId)
	)

	resp, err := DoRequest(
		cfg.GitlabIntegrationUrl+"/api/v4/projects/"+strProjectId+"/variables",
		cfg.GitlabIntegrationToken,
		http.MethodPost,
		data,
	)
	if err != nil {
		return GitlabIntegrationResponse{}, err
	}

	if resp.Code >= 500 {
		return GitlabIntegrationResponse{}, errors.New(status.InternalServerError.Description)
	}

	if resp.Code >= 400 {
		msgBytes, _ := json.Marshal(resp.Message)
		return GitlabIntegrationResponse{}, fmt.Errorf("gitlab error %d: %s", resp.Code, string(msgBytes))
	}

	return resp, nil
}

func MakeGitLabRequest(method, url string, payload map[string]any, token string) (*http.Response, error) {
	reqBody := new(bytes.Buffer)
	if payload != nil {
		json.NewEncoder(reqBody).Encode(payload)
	}

	req, err := http.NewRequest(method, url, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+token)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func DeleteForkedProject(repoName string, cfg config.Config) (response GitlabIntegrationResponse, err error) {
	url := cfg.GitlabIntegrationURL + "/api/v4/projects/ucode%2Fucode_micro_frontend%2F" + repoName

	resp, err := DoRequest(url, cfg.GitlabTokenMicroFront, http.MethodDelete, nil)
	if err != nil {
		return GitlabIntegrationResponse{}, err
	}

	if resp.Code >= 500 {
		return GitlabIntegrationResponse{}, errors.New(status.InternalServerError.Description)
	}

	if resp.Code >= 400 {
		msgBytes, _ := json.Marshal(resp.Message)
		return GitlabIntegrationResponse{}, fmt.Errorf("gitlab error %d: %s", resp.Code, string(msgBytes))
	}

	return GitlabIntegrationResponse{
		Code:    200,
		Message: map[string]any{"message": "Successfully deleted"},
	}, nil
}

// Integration gitlab.com

func RefreshGitLabToken(request GitLabTokenRequest) (*GitLabTokenResponse, error) {
	client := &http.Client{}

	requestBody, err := json.Marshal(map[string]string{
		"grant_type":    "refresh_token",
		"refresh_token": request.RefreshToken,
		"client_id":     request.ClinetId,
		"client_secret": request.ClientSecret,
	})
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, "https://gitlab.com/oauth/token", bytes.NewBuffer(requestBody))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var tokenResponse GitLabTokenResponse

	if err = json.Unmarshal(body, &tokenResponse); err != nil {
		return nil, err
	}

	return &tokenResponse, nil
}

func ListWebhooks(cfg WebhookConfig) (bool, error) {
	var apiURL = fmt.Sprintf("%s/api/v4/projects/%d/hooks", cfg.BaseUrl, cfg.RepoId)

	req, err := http.NewRequest(http.MethodGet, apiURL, nil)
	if err != nil {
		return false, err
	}

	req.Header.Set("Authorization", "Bearer "+cfg.Token)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("failed to list webhooks")
	}

	var webhooks []Webhook
	err = json.NewDecoder(resp.Body).Decode(&webhooks)
	if err != nil {
		return false, err
	}

	for _, webhook := range webhooks {
		if strings.HasPrefix(webhook.URL, cfg.ProjectUrl) {
			return true, nil
		}
	}

	return false, nil
}

func CreateWebhook(cfg WebhookConfig) error {
	var (
		apiURL  = fmt.Sprintf("%s/api/v4/projects/%d/hooks", cfg.BaseUrl, cfg.RepoId)
		webhook = WebhookRequest{
			URL:                    fmt.Sprintf("%s/v2/webhook/handle?project_id=%s&resource_id=%s&environment_id=%s", cfg.ProjectUrl, cfg.ProjectId, cfg.ResourceId, cfg.EnvironmentId),
			PushEvents:             true,
			MergeRequestsEvents:    true,
			TagPushEvents:          true,
			EnableSSLVerification:  true,
			ConfidentialNoteEvents: false,
			IssuesEvents:           false,
			NoteEvents:             false,
			PipelineEvents:         false,
			WikiPageEvents:         false,
		}
	)

	payload, err := json.Marshal(webhook)
	if err != nil {
		return fmt.Errorf("failed to marshal webhook payload: %v", err)
	}

	req, err := http.NewRequest(http.MethodPost, apiURL, bytes.NewBuffer(payload))
	if err != nil {
		return fmt.Errorf("failed to create HTTP request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+cfg.Token)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send HTTP request: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("failed to create webhook: %s", string(body))
	}

	return nil
}

func ImportFromGitlabCom(cfg ImportData) (response github.ImportResponse, err error) {
	gitlabBodyJSON, err := json.Marshal(cfg)
	if err != nil {
		return github.ImportResponse{}, errors.New("failed to marshal JSON")
	}

	gitlabUrl := "https://gitlab.udevs.io/api/v4/import/gitlab"
	req, err := http.NewRequest(http.MethodPost, gitlabUrl, bytes.NewBuffer(gitlabBodyJSON))
	if err != nil {
		return github.ImportResponse{}, errors.New("failed to create request")
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("PRIVATE-TOKEN", cfg.GitlabToken)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return github.ImportResponse{}, errors.New("failed to send request")
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return github.ImportResponse{}, errors.New("failed to read response body")
	}

	var importResponse github.ImportResponse

	if err = json.Unmarshal(respBody, &importResponse); err != nil {
		return github.ImportResponse{}, errors.New("failed to unmarshal response body")
	}

	return importResponse, nil
}

func IsExpired(createdAt int64, expiresIn int32) bool {
	createdTime := time.Unix(createdAt, 0) // Convert Unix timestamp to time.Time
	expirationTime := createdTime.Add(time.Duration(expiresIn) * time.Second)
	return time.Now().After(expirationTime)
}

func ImportFromGitLab(cfg ImportData) (response github.ImportResponse, err error) {
	err = ExportRepo(cfg)
	if err != nil {
		return github.ImportResponse{}, err
	}

	err = checkExportStatusWithTimeout("https://gitlab.com/api/v4/projects", cfg.RepoId, cfg.PersonalAccessToken)
	if err != nil {
		return github.ImportResponse{}, err
	}

	err = exportProject(fmt.Sprintf("https://gitlab.com/api/v4/projects/%v/export/download", cfg.RepoId), cfg.PersonalAccessToken, cfg.NewName+".tar.gz")
	if err != nil {
		return github.ImportResponse{}, err
	}

	url := "https://gitlab.udevs.io/api/v4/projects/import"

	importResponse, err := ImportGitLabProject(cfg.GitlabToken, url, fmt.Sprintf("%d", cfg.GitlabGroupId), cfg.NewName, cfg.NewName+".tar.gz")
	if err != nil {
		return github.ImportResponse{}, err
	}

	//remove file
	err = os.Remove(cfg.NewName + ".tar.gz")
	if err != nil {
		return github.ImportResponse{}, err
	}

	// Parse response into ImportResponse struct

	return importResponse, nil
}

func ExportRepo(cfg ImportData) error {
	url := fmt.Sprintf("https://gitlab.com/api/v4/projects/%s/export", cfg.RepoId)
	req, err := http.NewRequest(http.MethodPost, url, nil)
	if err != nil {
		return err
	}

	// Set Authorization Header
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", cfg.PersonalAccessToken))

	// Send Request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusAccepted {
		return errors.New("failed to export repository")
	}

	// Read Response
	return nil
}

func exportProject(exportURL, gitlabToken, exportFilePath string) error {
	req, err := http.NewRequest(http.MethodGet, exportURL, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Add("Authorization", "Bearer "+gitlabToken)

	client := &http.Client{}

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}

	file, err := os.Create(exportFilePath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	_, err = io.Copy(file, resp.Body)
	if err != nil {
		return fmt.Errorf("failed to write to file: %w", err)
	}

	return nil
}

func ImportGitLabProject(token, url, namespace, path, filePath string) (github.ImportResponse, error) {
	// Open the file
	file, err := os.Open(filePath)
	if err != nil {
		return github.ImportResponse{}, fmt.Errorf("error opening file: %w", err)
	}
	defer file.Close()

	// Create a buffer to store multipart form data
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Add namespace and path fields
	_ = writer.WriteField("namespace", namespace)
	_ = writer.WriteField("path", path)

	// Add file to the form
	part, err := writer.CreateFormFile("file", filePath)
	if err != nil {
		return github.ImportResponse{}, fmt.Errorf("error creating form file: %w", err)
	}

	// Copy file content to multipart writer
	_, err = io.Copy(part, file)
	if err != nil {
		return github.ImportResponse{}, fmt.Errorf("error copying file content: %w", err)
	}

	// Close the writer to finalize the form
	writer.Close()

	// Create the request
	req, err := http.NewRequest("POST", url, body)
	if err != nil {
		return github.ImportResponse{}, fmt.Errorf("error creating request: %w", err)
	}

	// Set headers
	req.Header.Set("PRIVATE-TOKEN", token)
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// Send request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return github.ImportResponse{}, fmt.Errorf("error sending request: %w", err)
	}
	defer resp.Body.Close()

	// Check response status
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return github.ImportResponse{}, fmt.Errorf("failed to import project, status: %s", resp.Status)
	}

	respByte, err := io.ReadAll(resp.Body)
	if err != nil {
		return github.ImportResponse{}, err
	}

	var importResponse github.ImportResponse
	if err = json.Unmarshal(respByte, &importResponse); err != nil {
		return github.ImportResponse{}, errors.New("failed to unmarshal response body")
	}

	return importResponse, nil
}

// GetRepoCodebase returns all relevant source files from a GitLab repository.
// Always reads from UGenBranch ("u-gen"). If the branch does not exist,
// it is created from DefaultBranch ("master") first.
// Uses the GitLab archive API (single request) instead of per-file requests for speed.
func GetRepoCodebase(gitlabURL, token string, projectID int) ([]RepoFile, error) {
	client, err := gitlab.NewClient(token, gitlab.WithBaseURL(gitlabURL+"/api/v4"))
	if err != nil {
		return nil, fmt.Errorf("failed to create gitlab client: %w", err)
	}

	if err = ensureUGenBranch(client, projectID); err != nil {
		return nil, err
	}

	return fetchArchiveFiles(gitlabURL, token, projectID, config.UGenBranch)
}

// ensureUGenBranch checks if UGenBranch exists; creates it from DefaultBranch if not.
func ensureUGenBranch(client *gitlab.Client, projectID int) error {
	_, _, err := client.Branches.GetBranch(projectID, config.UGenBranch)
	if err == nil {
		return nil
	}

	_, _, err = client.Branches.CreateBranch(projectID, &gitlab.CreateBranchOptions{
		Branch: gitlab.Ptr(config.UGenBranch),
		Ref:    gitlab.Ptr(config.DefaultBranch),
	})
	if err != nil {
		return fmt.Errorf("failed to create branch %q from %q: %w", config.UGenBranch, config.DefaultBranch, err)
	}

	return nil
}

// fetchArchiveFiles downloads the repo as a tar.gz archive (single HTTP request)
// and extracts only the relevant source files, skipping CI/CD configs, OS junk, and binaries.
func fetchArchiveFiles(gitlabURL, token string, projectID int, branch string) ([]RepoFile, error) {
	url := fmt.Sprintf("%s/api/v4/projects/%d/repository/archive.tar.gz?sha=%s", gitlabURL, projectID, branch)

	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("PRIVATE-TOKEN", token)

	httpClient := &http.Client{Timeout: 60 * time.Second}
	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gitlab archive request failed with status %d: %s", resp.StatusCode, string(body))
	}

	gzr, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to create gzip reader: %w", err)
	}
	defer gzr.Close()

	tr := tar.NewReader(gzr)

	var files []RepoFile
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("failed to read tar archive: %w", err)
		}

		if header.Typeflag != tar.TypeReg {
			continue
		}

		// Strip the leading directory added by GitLab (projectname-branch-sha/file.go)
		parts := strings.SplitN(header.Name, "/", 2)
		if len(parts) < 2 || parts[1] == "" {
			continue
		}
		filePath := parts[1]

		if shouldSkipFile(filePath) {
			continue
		}

		content, err := io.ReadAll(tr)
		if err != nil {
			continue
		}

		files = append(files, RepoFile{
			Path:    filePath,
			Content: string(content),
		})
	}

	return files, nil
}

// shouldSkipFile returns true for files that are not useful for frontend preview:
// CI/CD configs, OS metadata, binary assets, and Go dependency lock files.
var (
	skipFileNames = map[string]bool{
		".DS_Store":          true,
		".gitlab-ci.yml":     true,
		"func.yaml":          true,
		"go.sum":             true,
		".gitignore":         true,
		".gitkeep":           true,
		"package.json":       true,
		"package-lock.json":  true,
		"yarn.lock":          true,
		"pnpm-lock.yaml":     true,
		"Dockerfile":         true,
		"Makefile":           true,
		"vite.config.js":     true,
		"vite.config.ts":     true,
		"tsconfig.json":      true,
		"tsconfig.app.json":  true,
		"tsconfig.node.json": true,
	}

	skipDirPrefixes = []string{
		"gitlab/",
		".git/",
		".gitlab/",
	}

	skipExtensions = map[string]bool{
		".png": true, ".jpg": true, ".jpeg": true, ".gif": true,
		".ico": true, ".webp": true, ".bmp": true,
		".woff": true, ".woff2": true, ".ttf": true, ".eot": true, ".otf": true,
		".zip": true, ".tar": true, ".gz": true, ".jar": true,
		".exe": true, ".bin": true, ".dll": true, ".so": true, ".dylib": true,
		".pdf": true, ".doc": true, ".docx": true,
	}
)

func shouldSkipFile(path string) bool {
	return ShouldSkipFile(path)
}

// ShouldSkipFile returns true for files that must not be pushed by AI generation:
// package.json/lock, config files, CI/CD, OS metadata, binaries.
// Exported so handlers can filter before calling CommitFiles.
func ShouldSkipFile(path string) bool {
	base := filepath.Base(path)
	if skipFileNames[base] {
		return true
	}

	for _, prefix := range skipDirPrefixes {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}

	ext := strings.ToLower(filepath.Ext(path))
	return skipExtensions[ext]
}

func checkExportStatusWithTimeout(baseURL, projectID, exportToken string) error {
	url := fmt.Sprintf("%s/%s/export", baseURL, projectID)
	startTime := time.Now()
	maxWait := 30 * time.Minute

	for {
		if time.Since(startTime) > maxWait {
			return fmt.Errorf("export timed out after %v", maxWait)
		}

		req, _ := http.NewRequest(http.MethodGet, url, nil)
		req.Header.Set("Authorization", "Bearer "+exportToken)

		client := &http.Client{}
		resp, err := client.Do(req)
		if err != nil {
			return err
		}

		var result map[string]string
		json.NewDecoder(resp.Body).Decode(&result)
		resp.Body.Close() // ← явный Close вместо defer внутри цикла

		if result["export_status"] == "finished" {
			return nil
		}

		time.Sleep(10 * time.Second)
	}
}
